version: "3.8"

services:
  server:
    logging:
      driver: gcplogs
    image: gcr.io/${PROJECT_ID}/youtube-backend:${IMAGE_TAG}
    ports:
      - "8800:8800"
    environment:
      - MONGO=${MONGO}
      - JWT=${JWT}
    restart: unless-stopped

  client:
    logging:
      driver: gcplogs
    image: gcr.io/${PROJECT_ID}/youtube-frontend:${IMAGE_TAG}
    ports:
      - "80:80"
    environment:
      - REACT_APP_FIREBASE_API_KEY=${REACT_APP_FIREBASE_API_KEY}
    restart: unless-stopped
    depends_on:
      - server

volumes:
  mydata:
